version: "3"

services:

  s_cons:
    build:
      context: .
      dockerfile: Dockerfile_c
    container_name: s_cons

  s_prod:
    build:
      context: .
      dockerfile: Dockerfile_p
    container_name: s_prod
